# ============================================================
#  ldap-service — OpenLDAP
# ============================================================
apiVersion: v1
kind: Secret
metadata:
  name: ldap-secret
  namespace: inventario
type: Opaque
stringData:
  admin-password: "LdapAdmin#2025"   # cambiar en producción
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldap-service
  namespace: inventario
  labels:
    app: ldap-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ldap-service
  template:
    metadata:
      labels:
        app: ldap-service
    spec:
      containers:
        - name: ldap-service
          image: osixia/openldap:1.5.0
          ports:
            - containerPort: 389
            - containerPort: 636
          env:
            - name: LDAP_ORGANISATION
              value: "ITU"
            - name: LDAP_DOMAIN
              value: "itu.edu"
            - name: LDAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ldap-secret
                  key: admin-password
            - name: LDAP_TLS
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: ldap-service
  namespace: inventario
spec:
  type: ClusterIP
  selector:
    app: ldap-service
  ports:
    - name: ldap
      port: 389
      targetPort: 389
    - name: ldaps
      port: 636
      targetPort: 636
